# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/oneplus6t/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter oneplus6t,$(TARGET_DEVICE)),)

endif
